name: Lint and test the package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: check formatting
        uses: dx-oss/nix-shell-action@v11
        with:
          script: |
            pre-commit run --all-files

      - name: elm-test
        uses: dx-oss/nix-shell-action@v11
        with:
          script: |
            elm-test

      - name: elm-review
        uses: dx-oss/nix-shell-action@v11
        with:
          script: |
            elm-review
